### ISSUE TITLE
Blank output when using predict()

### ISSUE THREAD

**Issue by sfregosi** [EricArcher/banter#4]
Hi Eric,

Moving my question over on [BA Stack Exchange](https://bioacoustics.stackexchange.com/questions/1338/error-when-using-predict-function-in-r-package-banter-for-click-classification) here because I made some progress but am stuck again now...

My first issue was that I was not loading the `rfPermute` package but when I did that I am now able to successfully run:

`score <- predict(bant.mdl, dets_banter)`

but `score` ends up blank. 

I am working with a model that was made from acoustic features extracted with an older version of `PAMpal`, to predict acoustic features extracted with the latest version of `PAMpal`. That led to one issue with feature column names not matching perfectly, but I was able to manually fix that. From what I can tell to-be-predicted events (exported for `banter` by `PAMpal`) are in the right format. 

In trying to examine my `bant.mdl` to make sure it looks ok, I wasn't able to use the `banter::summary` function. That throws the below error. I suspect this is from [ths update](https://github.com/EricArcher/banter/commit/31276ec139646927d30b7abc02879e668fae8aac) but maybe you can confirm. 

```
Error in FUN(X[[i]], ...) : 
  no slot of name "timestamp" for this object of class "banter_detector"
```

Thank you!
Selene

**Comment by sfregosi** [comment]
Also, I'm emailing you my model and detections as a combined .rda now!

**Comment by EricArcher** [comment]
The error is due to the fact that the detector models in your banter model object do not have @timestamp slots in them. From the code, I can't work out why this should be. The example code works, so I know that in normal operations, these slots get filled correctly. 

Can you show me the code you used to create these detector models? Also, did you happen to create these models with a version of `banter` prior to when I added the @timestamp slot?

**Comment by TaikiSan21** [comment]
`export_banter` has a `training` argument, default is `TRUE`. If you instead do `export_banter(data, training=FALSE)` it should export all your data without complaining about the "not enough events" stuff. 

The prediction score thing not working unless you put in a dummy variable is weird, but I think I figured it out. Since the PAMpal default is to put a placeholder `NA` as the species ID until it gets set, this is what gets exported. This is causing problems in `banter::predict` [here](https://github.com/EricArcher/banter/blob/e504651b6605b5d682c141cb4afb314d085adc79/R/predict.R#L195) because any row with any `NA` value is getting dropped. @EricArcher, do you think this line should get modified to exclude the `species` column from the `NA` checking? I could imagine a scenario where a user only has labels for some of their data, so the `species` column would be a mix of `NA` and actual labels.

**Comment by sfregosi** [comment]
aha! Of course the `training` argument is already an option. Thanks for pointing me to that and I'll incorporate that into my regular 'predict-only' flow.

**Comment by EricArcher** [comment]
It looks like it would suffice to have `banter::predict` drop the `species` column altogether at the beginning of the function. If that sounds good to ya'll I'll do it and push up a new version.

**Comment by EricArcher** [comment]
Belay that last. That won't work. Taiki's solution of having the na.omit line ignore the species column is better

**Comment by EricArcher** [comment]
There's a secondary problem: `banter::predict` assumes that if the species column is present, that you want to do a comparison between assumed species and predicted species IDs, adding a column to the `$predict.df` element of the output identifying if that comparison is correct. If species is `NA`, the output of that is weird. I'l edit it to make the results of all of that `NA`.

**Comment by EricArcher** [comment]
Edits have been pushed. @sfregosi would you give it a shot?

**Comment by sfregosi** [comment]
Thank you, both! All looks to be working great. 

Tried with no manual 'species' column in my detection events csv (`export_banter` gives NAs for all events) - got prediction scores and the `original` and `correct` columns both are populated with NAs (as expected!) 

Tried with manually ID'd species column in detection events (but exported for banter with `training = FALSE`) - got prediction scores and `original` and `correct` columns with the original entries and TRUE/FALSE as expected!

**Comment by EricArcher** [comment]
Excellent! Let me know if you run into anything else.
